apiVersion: v1
kind: Secret
metadata:
  name: postgresql-account-secret
  namespace: habo-banking
type: Opaque
stringData:
  POSTGRES_USER: habouser
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: account_db
