services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres-account:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: account_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  service-account-app:
    build:
      context: ../services/service-account
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgres-account
      POSTGRES_DB: account_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      postgres-account:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  service-account-consumer:
    build:
      context: ../services/service-account
      dockerfile: Dockerfile
    command: python manage.py consume_events
    environment:
      POSTGRES_HOST: postgres-account
      POSTGRES_DB: account_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      service-account-app:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: on-failure
