DISABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - SPELL_LYCHEE
  - REPOSITORY_KICS
  - TYPESCRIPT_STANDARD
  - REPOSITORY_TRIVY
  - REPOSITORY_GRYPE
  - COPYPASTE_JSCPD
  - PYTHON_MYPY
  - PYTHON_PYRIGHT

PYTHON_PYLINT_CONFIG_FILE: services/service-account/.pylintrc

YAML_V8R_FILTER_REGEX_EXCLUDE: "infrastructure/docker-local/grafana/|infrastructure/docker-local/loki-config\\.yaml|infrastructure/docker-local/prometheus-config\\.yaml"
