FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

COPY ["service-auth.csproj", "./"]
RUN dotnet restore "./service-auth.csproj"

COPY ["Program.cs", "./"]
COPY ["appsettings.json", "./"]
COPY ["appsettings.Development.json", "./"]
COPY ["Controllers/", "./Controllers/"]
COPY ["Services/", "./Services/"]
COPY ["Properties/", "./Properties/"]

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Development

ENTRYPOINT ["dotnet", "watch", "run", "--project", "service-auth.csproj", "--urls", "http://+:8080"]
