services:
  ai-service-dev-container:
    image: mcr.microsoft.com/devcontainers/dotnet:9.0
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so you will mount '..'. You would then reference this path as the
      # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ../../..:/workspace:cached

    command: sleep infinity
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq

  rabbitmq:
    image: rabbitmq:4-management-alpine
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  rabbitmq-data:
