[mypy]
ignore_errors = True
mypy_path = .
explicit_package_bases = True
namespace_packages = True
exclude = (?x)(migrations/|__pycache__/)

[mypy-django.*]
ignore_missing_imports = True

[mypy-accounts.*]
ignore_missing_imports = True