apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: habo-banking
spec:
  selector:
    app: service-frontend
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 80
