services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_AUTH_API_URL: ${AuthServiceUrl}
        VITE_ACCOUNT_API_URL: ${AccountServiceUrl}
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
