apiVersion: v1
kind: Service
metadata:
  name: service-currency-exchange-metrics
  namespace: habo-banking
spec:
  selector:
    app: service-currency-exchange
  type: ClusterIP # Internal only — scraped by Prometheus
  ports:
    - port: 9093
      targetPort: 9093
