services:
  service-auth:
    image: service-auth
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${AuthServicePort:-8080}:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
