apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: habo-banking
spec:
  selector:
    app: mongodb
  type: ClusterIP # Internal only
  ports:
    - port: 27017
      targetPort: 27017
