apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-ai
  namespace: habo-banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-ai
  template:
    metadata:
      labels:
        app: service-ai
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.37
          command:
            [
              "sh",
              "-c",
              "until nc -z rabbitmq 5672; do echo 'waiting for rabbitmq...'; sleep 2; done",
            ]
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
              ephemeral-storage: "16Mi"
            limits:
              cpu: "50m"
              memory: "32Mi"
              ephemeral-storage: "32Mi"
      containers:
        - name: service-ai
          image: forkeh/habo-bank-service-ai:latest
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secret
                  key: OPENROUTER_API_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "512Mi"
