name: Frontend Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: services/service-frontend/package-lock.json

      - name: Install dependencies
        working-directory: "services/service-frontend"
        run: npm ci

      - name: Run tests
        working-directory: "services/service-frontend"
        run: npm run test

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: "services/service-frontend"
