name: Service Currency Exchange CI

permissions:
  pull-requests: write
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - services/service-currency-exchange/**
  pull_request:
    paths:
      - services/service-currency-exchange/**

jobs:
  run-tests:
    uses: ./.github/workflows/service-currency-exchange-tests.yml
    secrets: inherit
  dockerize:
    needs: run-tests
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/dockerize.yml
    with:
      docker-image-name: service-currency-exchange
    secrets:
      DOCKER_USERNAME: ${{ secrets.BRIAN_DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.BRIAN_DOCKER_PASSWORD }}
