name: AuthService CI/CD

permissions:
  pull-requests: write

on:
  push:
      paths:
        - "services/service-auth/**"
        - ".github/workflows/service-auth.yml"
        - ".github/workflows/service-auth-tests.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "services/service-auth/**"
      - ".github/workflows/service-auth.yml"
      - ".github/workflows/service-auth-tests.yml"
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/service-auth-tests.yml
  dockerize:
    needs: run-tests
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/dockerize.yml
    with:
      docker-image-name: service-auth
    secrets:
      DOCKER_USERNAME: ${{ secrets.OLIVIA_DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.OLIVIA_DOCKER_PASSWORD }}
