name: Service AI CI

permissions:
  pull-requests: write
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - services/service-ai/**
  pull_request:
    paths:
      - services/service-ai/**

jobs:
  run-tests:
    uses: ./.github/workflows/service-ai-tests.yml
    secrets: inherit
  dockerize:
    needs: run-tests
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/service-ai-dockerize.yml
    secrets: inherit
