name: Service Currency Exchange CI

permissions:
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - services/service-currency-exchange/**
  pull_request:
    paths:
      - services/service-currency-exchange/**

jobs:
  run-tests:
    uses: ./.github/workflows/service-currency-exchange-tests.yml
