name: AuthService CI/CD

on:
  pull_request:
    branches: [ main ]
    paths:
      - "services/service-auth/**"
      - ".github/workflows/service-auth.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore dependencies
        run: dotnet restore services/service-auth/test/test.csproj

      - name: Build
        run: dotnet build services/service-auth/test/test.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test services/service-auth/test/test.csproj --configuration Release --no-build --verbosity normal