name: Service AI CI

permissions:
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - services/service-ai/**
  pull_request:
    paths:
      - services/service-ai/**

jobs:
  run-tests:
    uses: ./.github/workflows/service-ai-tests.yml
