name: Service Account CI

permissions:
  pull-requests: write
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - services/service-account/**
  pull_request:
    paths:
      - services/service-account/**

jobs:
  run-tests:
    uses: ./.github/workflows/service-account-tests.yml

  dockerize:
    needs: run-tests
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/dockerize.yml
    with:
      docker-image-name: service-account
    secrets:
      DOCKER_USERNAME: ${{ secrets.HS_DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.HS_DOCKER_PASSWORD }}
